name: pr
on: [pull_request]
jobs:
  test:
    name: 'Test (node ${{ matrix.node }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: pnpm install --legacy-peer-deps

      - name: Build the Project
        run: pnpm run build

      - name: Running Typechecks
        run: pnpm run typecheck

      - name: Running Tests
        run: pnpm run test
